module.exports = [
    "The only way to do great work is to love what you do.",
    "Consistency over time leads to excellence.",
    "In the midst of difficulty lies opportunity.",
    "Your attitude determines your direction.",
    "Focus on progress, not perfection.",
    "The best way to predict the future is to create it.",
    "Strive for progress, not perfection.",
    "Action is the foundational key to all success.",
    "Don't watch the clock; do what it does. Keep going.",
    "Opportunities don't happen. You create them.",
    "The future depends on what you do today.",
    "Innovate relentlessly, create abundantly.",
    "Think big, act decisively, and hustle persistently.",
    "Be a visionary in a world of conformists; disrupt, innovate, dominate.",
    "Embrace failure as a stepping stone to success, not a stumbling block.",
    "The key to success is to focus on goals that inspire and motivate you.",
    "Strive for mastery in your craft, and success will follow suit.",
    "Your wealth grows in proportion to the problems you solve for others.",
    "Wealth is the byproduct of solving problems and adding value at scale.",
    "Elevate others; elevate yourself.",
    "Optimism fuels success.",
    "Wealth is a mindset.",
    "Invest in your joy.",
    "Chase dreams, not dollars.",
    "Think big, stay humble.",
    "Impact over income.",
    "Gratitude breeds wealth.",
    "Success loves positivity.",
    "Rich in purpose, not just riches.",
    "Strive not to be a success, but rather to be of value.",
    "Eighty percent of success is showing up.",
    "Winning isn’t everything, but wanting to win is.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "You can never cross the ocean until you have the courage to lose sight of the shore",
    "People often say that motivation doesn’t last. Well, neither does bathing. That’s why we recommend it daily",
    "Life shrinks or expands in proportion to one’s courage.",
    "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.",
    "The only way to do great work is to love what you do.",
    "Believe you can and you're halfway there.",
    "The only way to do anything is to start",
    "The only way to do it is to do it.",
    "The only way to do something in depth is to work hard.",
    "The only thing that is constant is change.",
    "The only source of knowledge is experience.",
    "I have not failed. I've just found 10,000 ways that won't work.",
    "Legacy is greater than currency.",
    "The best marketing doesn't feel like marketing.",
    "Success is doing what you want, when you want, where you want, with whom you want, as much as you want.",
    "People don't buy what you do; they buy why you do it.",
    "Ideas are easy. Implementation is hard",
    "The best way to stand out is to be known for something specific",
    "Your calendar never lies.",
    "Greatness is not what you have, it's what you give",
    "The best way to predict the future is to create it.",
    "Your time is limited, so don’t waste it living someone else’s life",
    "The best way to predict the future is to invent it.",
    "If you cannot do great things, do small things in a great way.",
    "Success is not what you have, but who you are.",
    "I’ve failed over and over and over again in my life. And that is why I’ve been successful.",
    "The success of every woman should be the inspiration to another. We should raise each other up.",
    "Don’t count the days; make the days count.",
    "Success breeds confidence.",
    "You have to fight to reach your dream. You have to sacrifice and work hard for it.",
    "You have to believe in yourself when no one else does.",
    "I didn’t come this far to only come this far, so we’ve still got further to go.",
    "I like criticism. It makes you strong.",
    "The strength of the team is each individual member. The strength of each member is the team",
    "I’d rather regret the risks that didn’t work out than the chances I didn’t take at all.",
    "It’s not whether you get knocked down, it’s whether you get up.",
    "It is better to look ahead and prepare than to look back and regret.",
    "I think you have different challenges in your life, and how you approach those challenges is what defines you.",
    "The strength of the team is each individual member. The strength of each member is the team.",
    "Your love makes me strong, your hate makes me unstoppable.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "Follow your passion. Stay true to yourself. Never follow someone else’s path unless you’re in the woods and you’re lost and you see a path. By all means, you should follow that.",
    "People haven't always been there for me, but music always has.",
    "I raise up my voice—not so I can shout, but so that those without a voice can be heard.",
    "Life is not fair; it never was and it never will be. Do not fall into the trap—the entitlement trap, of feeling like you’re a victim.",
    "I can do this all day",
    "I choose to run toward my problems, and not away from them. Because that’s what heroes do.",
    "I’ve been compromised. I’ve got a lot of red in my ledger. I’d like to wipe it out.",
    "With great power comes great responsibility.",
    "That's my secret, Captain: I'm always angry.",
    "Don’t take rest after your first victory because if you fail in the second, more lips are waiting to say that your first victory was just luck.",
    "It's important to learn and not repeat the same mistakes. What's done is done.",
    "I have never taken any decisions about my career, nor do I have any regrets",
    "Enjoy the game and chase your dreams. Dreams do come true.",
    "Don't let your fears become boxes that enclose you. Open them out, feel them, and turn them into the greatest courage you are capable of.",
    "I don’t believe in taking right decisions. I take decisions and then make them right.",
    "Arise, awake, and stop not until the goal is achieved.",
    "You can’t cross the sea merely by standing and staring at the water.",
    "Music is the only thing that will remain when everything is gone.",
    "You have to dream before your dreams can come true",
    "I believe that the success of any business is to go for the best.",
    "The policy of being too cautious is the greatest risk of all.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "In the journey of life, challenges are like the spices in a recipe. They make it interesting and worthwhile.",
    "Your time is limited, don't waste it living someone else's life.",
    "Success is not just about making money. It's about making a difference",
    "If you get to a position, there are hundreds waiting to pull you down. Be careful.",
    "Age is just a number. It gives me the experience, and the confidence to do what I want to do.",
    "In the journey of life, we pass pleasures and pain. There will be sunshine and rain; there will be loss and gain. But we must learn to smile again and again.",
];